name: Check Linting and Formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint mypy black isort

      - name: Run linting
        run: make lint

      - name: Run formatting
        run: make format