name: Check Linting and Formatting

on:
  push:
    branches:
      - '*'
  pull-request:
    branches:
      - master

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check linting
        run: make lint

      - name: Check formatting
        run: make check-formatting